_format_version: "2.1"
_transform: true

services:
  - name: view-service
    url: http://view:5000
    routes:
      - name: view-routes
        paths:
          - /.*
          - /
        strip_path: true

